# Generated by Django 4.1.3 on 2022-11-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='email',
            new_name='Email_usuario',
        ),
    ]
