# Generated by Django 4.1.3 on 2022-11-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0002_rename_email_familia_email_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
