# Generated by Django 4.1.3 on 2022-11-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0003_alter_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='Edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
